version: '2'
services:
  db:
    build:
      context: ${BASE_DIR}/deploy/dev/db
    ports:
    - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
  api:
    build:
      context: ${BASE_DIR}
      dockerfile: deploy/dev/api/Dockerfile
    ports:
    - '8000:8000'
    volumes:
    - ${BASE_DIR}/api:/src/api
    - ${GOROOT}:/go/
    environment:
      - ENVIRONMENT=${ENV}
    # logging:0
    #   driver: 'json-file'
    #   options:
    #     max-size: '200K'
    #     max-file: '5'
    links:
    - db
    # - redis
    depends_on:
    - db
  client:
    build:
      context: ${BASE_DIR}
      dockerfile: deploy/dev/client/Dockerfile
    ports:
    - '3000:3000'
    volumes:
    - ${BASE_DIR}/client:/src/client
    environment:
      - ENVIRONMENT=${ENV}
  # db:
  #   build: db
  #   ports:
  #     - '3306:3306'
    # volumes:
    #   - db-volume:/var/lib/mysql
  db-migrate:
    build: db-migrate
    links:
      - db
    depends_on:
      - db
    volumes:
      - ${BASE_DIR}/deploy/dev/db-migrate:/db-migrate
    environment:
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD : ${POSTGRES_PASSWORD}
  # haproxy:
  #   build: haproxy
  #   links:
  #     - api
  #     - ui
  #   ports:
  #     - '80:80'
  #     - '443:443'
  # redis:
  #   image: redis:3.2.1
  #   ports:
  #     - '6379:6379'

volumes:
  db-volume: